<?php

namespace Araneum\Bundle\MainBundle\Repository;

use Araneum\Bundle\MainBundle\Entity\Application;
use Doctrine\ORM\EntityRepository;

/**
 * ApplicationRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class ApplicationRepository extends EntityRepository
{
    /**
     * Get statistics of all applications by next conditions:
     *  - online
     *  - has problems
     *  - has errors
     *  - disabled
     *
     * return \stdClass
     */
    public function getApplicationsStatistics()
    {
        $qb = $this->createQueryBuilder('A');



        $qb->setParameters(
            [
                'online' => Application::STATUS_OK,
//                'hasProblem' => Application::STATUS_CODE_INCORRECT
            ]
        );

        echo $qb->getQuery()->getDQL();die;


        return;

//        return (object) $this->createQueryBuilder('A')
//            ->select('SUM(CASE WHEN A.enabled = TRUE AND A.status = :online THEN 1 ELSE 0 END) AS online')
//            ->addSelect('SUM(CASE WHEN A.enabled = TRUE AND A.status = :hasProblem THEN 1 ELSE 0 END) as hasProblems')
//            ->addSelect('SUM(CASE WHEN A.status > :hasProblem THEN 1 ELSE 0 END) as hasErrors')
//            ->addSelect('SUM(CASE WHEN A.enabled = FALSE THEN 1 ELSE 0 END) as disabled')
//            ->setParameters(
//                [
//                    'online' => Application::STATUS_OK,
//                    'hasProblem' => Application::STATUS_CODE_INCORRECT
//                ]
//            )
//            ->getQuery()
//            ->getOneOrNullResult();
    }
}
