services:
  araneum.customer.admin.customer:
      class: Araneum\Bundle\AgentBundle\Admin\CustomerAdmin
      tags:
          - { name: sonata.admin, manager_type: orm, group: "Customer", label: "Customer" }
      arguments:
          - ~
          - Araneum\Bundle\AgentBundle\Entity\Customer
          - ~
