services:
    araneum.agent.customer.api_handler:
        class: Araneum\Bundle\AgentBundle\Service\CustomerApiHandlerService
        arguments:
            - @araneum.main.application.manager
            - @doctrine.orm.entity_manager
            - @event_dispatcher
            - @form.factory
            - @araneum.agent.spotoption.service

    araneum.agent.spotoption.service:
        class: Araneum\Bundle\AgentBundle\Service\SpotOptionService
        arguments: [@araneum.base.rabbitmq.producer.spot, @araneum.base.spot_api, @doctrine.orm.entity_manager]

    araneum.agent.logger:
        class: Araneum\Bundle\AgentBundle\Service\AgentLoggerService
        arguments: [@doctrine.orm.entity_manager]

    araneum.agent.lead.api_handler:
        class: Araneum\Bundle\AgentBundle\Service\LeadApiHandlerService
        arguments: [@doctrine.orm.entity_manager, @form.factory]

    araneum.agent.customer.event_listener:
        class: Araneum\Bundle\AgentBundle\EventListener\CustomerListener
        arguments: [@araneum.agent.spotoption.service]
        tags:
            - { name: kernel.event_listener, event: araneum.agent.customer.new, method: onCreate }
            
    araneum.agent.error.api_handler:
        class: Araneum\Bundle\AgentBundle\Service\ErrorApiHandlerService
        arguments: [@doctrine.orm.entity_manager, @form.factory, @araneum.main.application.manager]