services:
    araneum.agent.customer.api_handler:
        class: Araneum\Bundle\AgentBundle\Service\CustomerApiHandlerService
        arguments: [@service_container]
        
    araneum.agent.spotoption.service:
        class: Araneum\Bundle\AgentBundle\Service\SpotOptionService
  
    araneum.agent.logger:
        class: Araneum\Bundle\AgentBundle\Service\AgentLoggerService
        arguments: [@doctrine.orm.entity_manager]