services:
    araneum.agent.customer.api_handler:
        class: Araneum\Bundle\AgentBundle\Service\CustomerApiHandlerService
        arguments:
            - @araneum.main.application.manager
            - @doctrine.orm.entity_manager
            - @event_dispatcher
            - @form.factory
            - @araneum.agent.spotoption.service

    araneum.agent.spotoption.service:
        class: Araneum\Bundle\AgentBundle\Service\SpotOptionService
        arguments: [@araneum.base.spot_api, %spot_api_public_url_login%]

    araneum.agent.logger:
        class: Araneum\Bundle\AgentBundle\Service\AgentLoggerService
        arguments: [@doctrine.orm.entity_manager]

    araneum.agent.lead.api_handler:
        class: Araneum\Bundle\AgentBundle\Service\LeadApiHandlerService
        arguments: [@doctrine.orm.entity_manager, @form.factory]