imports:
    - { resource: config_prod.yml }

framework:
    profiler: { only_exceptions: false }
    test: ~

doctrine:
   dbal:
       logging: "%kernel.debug%"

swiftmailer:
    disable_delivery: true
