imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: ../../src/Araneum/Base/Resources/config/services.yml }
    - { resource: rabbitmq.queue.yml }
    - { resource: daemons.yml }
    - { resource: ldap.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en
    locales: [en, ru]
    site_api:
        user: api
        password: QDurWe68
    rabbitmq_message_ttl: '20000'
    spot_enable_json_responce: true

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        handler_id:  snc_redis.session.handler
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        locales: %locales%

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: true
    filters:
        cssrewrite: ~

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_pgsql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        dql:
            datetime_functions:
                date_part: Araneum\Base\DoctrineFunctions\DatePart
            numeric_functions:
                cast: Araneum\Base\DoctrineFunctions\Cast
                round: Araneum\Base\DoctrineFunctions\Round

# Swiftmailer Configuration
swiftmailer:
    transport:  "%mailer_transport%"
    encryption: "%mailer_encryption%"
    auth_mode:  "%mailer_auth_mode%"
    host:       "%mailer_host%"
    username:   "%mailer_user%"
    password:   "%mailer_password%"
    spool:      { type: memory }

fos_user:
    db_driver: orm
    firewall_name: manage
    user_class: Araneum\Bundle\UserBundle\Entity\User

accelerator_cache:
    host: %domain%
    web_dir: %kernel.root_dir%/../web

fos_rest:
    param_fetcher_listener: true
    routing_loader:
        default_format: json
    view:
        view_response_listener: true
    disable_csrf_role: ROLE_API

nelmio_api_doc:
    sandbox:
        request_format:
            method: accept_header

lexik_maintenance:
    driver:
        class: '\Lexik\Bundle\MaintenanceBundle\Drivers\FileDriver' # class for file driver
        options: {file_path: %kernel.root_dir%/cache/lock}          # file_path is the complete path for create the file

old_sound_rabbit_mq:
    connections:
        default:
            host:     "%rabbitmq_host%"
            port:     "%rabbitmq_port%"
            user:     "%rabbitmq_user%"
            password: "%rabbitmq_password%"
            vhost:    '/'
            lazy:     true
            connection_timeout: 3
            read_write_timeout: 3

            keepalive: false
            heartbeat: 0
    producers:
        spot_customer:
            connection: default
            exchange_options:
                name: spot_customer_%session_prefix%
                type: direct
                auto_delete: false
                durable: true
            queue_options:
                name: spot_customer_%session_prefix%
                arguments:
                    "message-ttl": ['I', %rabbitmq_message_ttl%]
                    "dead-letter-exchange": ['S', 'araneum.base.rabbitmq.producer.spot_customer']
        spot:
            connection: default
            exchange_options:
                name: spot_%session_prefix%
                type: direct
                auto_delete: false
                durable: true
            queue_options:
                name: spot_%session_prefix%
                arguments:
                    "message-ttl": ['I', %rabbitmq_message_ttl%]
                    "dead-letter-exchange": ['S', 'araneum.base.rabbitmq.producer.spot']
        spot_login:
            connection: default
            exchange_options:
                name: spot_login_%session_prefix%
                type: direct
                auto_delete: false
                durable: true
            queue_options:
                name: spot_login_%session_prefix%
                arguments:
                    "message-ttl": ['I', %rabbitmq_message_ttl%]
                    "dead-letter-exchange": ['S', 'araneum.base.rabbitmq.producer.spot_login']
        application_customer:
            connection: default
            exchange_options:
                name: application_customer_%session_prefix%
                type: direct
                auto_delete: false
                durable: true
            queue_options:
                name: application_customer_%session_prefix%
                arguments:
                    "message-ttl": ['I', %rabbitmq_message_ttl%]
                    "dead-letter-exchange": ['S', 'araneum.base.rabbitmq.producer.application_customer']
    consumers:
        spot_customer:
            connection: default
            exchange_options:
                name: spot_customer_%session_prefix%
                type: direct
                auto_delete: false
                durable: true
            queue_options:
                name: spot_customer_%session_prefix%
            callback: araneum.base.rabbitmq.consumer.spot_customer
        spot:
            connection: default
            exchange_options:
                name: spot_%session_prefix%
                type: direct
                auto_delete: false
                durable: true
            queue_options:
                name: spot_%session_prefix%
            callback: araneum.base.rabbitmq.consumer.spot
        spot_login:
             connection: default
             exchange_options:
                 name: spot_login_%session_prefix%
                 type: direct
                 auto_delete: false
                 durable: true
             queue_options:
                 name: spot_login_%session_prefix%
             callback: araneum.base.rabbitmq.consumer.spot_login
        application_customer:
             connection: default
             exchange_options:
                 name: application_customer_%session_prefix%
                 type: direct
                 auto_delete: false
                 durable: true
             queue_options:
                 name: application_customer_%session_prefix%
             callback: araneum.base.rabbitmq.consumer.application_customer

snc_redis:
    clients:
        default:
            type: predis
            alias: default
            dsn: redis://localhost
            logging: %kernel.debug%
        session:
            type: predis
            alias: session
            dsn: redis://localhost/2
    session:
        client: session
        prefix: %session_prefix%
        ttl: 1200