parameters:
    daemons_iterate:
        araneum_daemon_check-site: 10 minutes
        araneum_daemon_spot-get-customers: 5 minutes

mik_software_daemon:
    daemons:
        araneum_daemon_consumer-spot:
            appName: spot-consumer
            appDescription: System Daemon for runuing Spot consumer
            appUser: %nginx_user%
            appGroup: %nginx_group%
            appPidDir: %kernel.root_dir%/daemons
            logVerbosity: 6

        araneum_daemon_consumer-login:
            appName: login-consumer
            appDescription: System Daemon for login to Spot consumer
            appUser: %nginx_user%
            appGroup: %nginx_group%
            appPidDir: %kernel.root_dir%/daemons
            logVerbosity: 6

        araneum_daemon_consumer-customer:
            appName: customer-consumer
            appDescription: System Daemon for sending Customers to Spot
            appUser: %nginx_user%
            appGroup: %nginx_group%
            appPidDir: %kernel.root_dir%/daemons
            logVerbosity: 6

        araneum_daemon_check-site:
            appName: check-site
            appDescription: System Daemon checker check.
            appUser: %nginx_user%
            appGroup: %nginx_group%
            appPidDir: %kernel.root_dir%/daemons
            logVerbosity: 6

        araneum_daemon_spot-get-customers:
            appName: spot-customers
            appDescription: System Daemon for get Customers from spot
            appUser: %nginx_user%
            appGroup: %nginx_group%
            appPidDir: %kernel.root_dir%/daemons
            logVerbosity: 6
