mik_software_daemon:
    daemons:
        araneum_consumer_spot:
            appName: spot-consumer
            appDescription: System Daemon for runuing Spot consumer
            appUser: %nginx_user%
            appGroup: %nginx_group%
            logVerbosity: 6

        araneum_consumer_login:
            appName: login-consumer
            appDescription: System Daemon for login to Spot consumer
            appUser: %nginx_user%
            appGroup: %nginx_group%
            logVerbosity: 6

        araneum_consumer_customer:
            appName: customer-consumer
            appDescription: System Daemon for sending Customers to Spot
            appUser: %nginx_user%
            appGroup: %nginx_group%
            logVerbosity: 6

        araneum_check_applications:
            appName: check_applications
            appDescription: System Daemon check all Apllications
            appUser: %nginx_user%
            appGroup: %nginx_group%

        araneum_check_connections:
            appName: check_connections
            appDescription: System Daemon check all Connections
            appUser: %nginx_user%
            appGroup: %nginx_group%

        araneum_check_runners:
            appName: check_runners
            appDescription: System Daemon check all Runners
            appUser: %nginx_user%
            appGroup: %nginx_group%

        araneum_check_clusters:
            appName: check_clusters
            appDescription: System Daemon check all Clusters
            appUser: %nginx_user%
            appGroup: %nginx_group%