parameters:
    ldap:
        service: app.ldap
        base_dn: uid=araneum,cn=sysaccounts,cn=etc,dc=office,dc=dev
        search_dn: cn=users,cn=accounts,dc=office,dc=dev
        search_password: LK8SoeTbffxFLDu5nOpY
        filter: (objectclass=*)
        user_role: ROLE_ADMIN
        user_password: 12345

services:
    api.ldap:
        class: Araneum\Bundle\MainBundle\Service\LdapService
        arguments: ["nova.office.dev"]

    api.ldap.synchronization:
        class: Araneum\Bundle\MainBundle\Service\LdapSynchronizationService
        arguments: [@doctrine.orm.entity_manager, @api.ldap, @service_container]