araneum_root:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: sonata_admin_dashboard
        permanent: true

araneum_locale:
    prefix: /{_locale}
    resource: routing_with_locale.yml
    defaults: {_locale: en}
    requirements:
        _locale: en|ru

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin