araneum_root:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: sonata_admin_dashboard
        permanent: true

araneum_locale:
    prefix: /{_locale}
    resource: routing_with_locale.yml
    defaults: {_locale: en}
    type: rad_convention
    requirements:
        _locale: %locales%

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

_knp_rad_assistant:
    resource: "@KnpRadBundle/Resources/config/routing/assistant.xml"
    prefix: /_assistant

araneum_main_api:
    resource: "@AraneumMainBundle/Controller/Api"
    type: annotation
    prefix: /{_locale}/api
    defaults: {_format: json, _locale: en}

araneum_customers_api:
    resource: "@AraneumCustomerBundle/Controller"
    type:     annotation
    prefix:   /{_locale}/api
    defaults: {_format: json, _locale: en}