araneum_root:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: sonata_admin_dashboard
        permanent: true

araneum_locale:
    prefix: /{_locale}
    resource: routing_with_locale.yml
    defaults: {_locale: en}
    type: rad_convention
    requirements:
        _locale: %locales%

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

_knp_rad_assistant:
    resource: "@KnpRadBundle/Resources/config/routing/assistant.xml"
    prefix: /_assistant

api:
    resource: '@AraneumMainBundle/Controller/ApplicationApiController.php'
    type: rest
    defaults: {_format: json}