araneum_user:
    resource: "@AraneumUserBundle/Controller/"
    type:     annotation
    prefix:   /

araneum_main:
    resource: "@AraneumMainBundle/Controller/"
    type:     annotation
    prefix:   /

