araneum_manage_login_check:
    pattern: /login_check
    defaults:
        _controller: FOSUserBundle:Security:check

araneum_manage_logout:
    pattern: /logout
    defaults:
        _controller: FOSUserBundle:Security:logout

araneum_user:
    resource: @AraneumUserBundle/Controller
    type: annotation

araneum_manage_main:
    pattern: /{_params}
    defaults:
        _controller: AraneumMainBundle:Default:admin
        _params: ~
    requirements:
        _params: .*