araneum_manage_login:
    pattern: /login
    condition: "request.isXmlHttpRequest()"
    defaults:
        _controller: FOSUserBundle:Security:login

araneum_manage_login_check:
    pattern: /login_check
    condition: "request.isXmlHttpRequest()"
    defaults:
        _controller: FOSUserBundle:Security:check

araneum_manage_logout:
    pattern: /logout
    condition: "request.isXmlHttpRequest()"
    defaults:
        _controller: FOSUserBundle:Security:logout

araneum_user:
    resource: "@AraneumUserBundle/Controller"
    type: annotation

araneum_manage_main:
    pattern: /{_params}
    condition: "!request.isXmlHttpRequest()"
    defaults:
        _controller: AraneumMainBundle:Default:admin
        _params: ~
    requirements:
        _params: .*