security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
            ROLE_ADMIN: [ROLE_USER, ROLE_SONATA_ADMIN]
            ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_API]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        api:
            pattern: ^/.*/api
            anonymous: ~
            http_basic:
                realm: "Araneum.Core API secure"
            stateless: true

        manage:
            pattern: ^/manage
            anonymous: ~
            entry_point: araneum_authentication

        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                default_target_path: sonata_admin_dashboard
                csrf_provider: security.csrf.token_manager
                success_handler: araneum.user.authentication_handler
                failure_handler: araneum.user.authentication_handler
            anonymous: true
            logout:
                path: fos_user_security_logout
                target: sonata_admin_dashboard

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/[a-zA-Z]+/admin/, role: ROLE_ADMIN }
        - { path: ^/admin/, role: ROLE_ADMIN }
#        - { path: ^/.*/api, role: ROLE_API }