services:
    araneum.main.admin.locale:
        class: Araneum\Bundle\MainBundle\Admin\LocaleAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Main", label: "Locale" }
        arguments:
            - ~
            - Araneum\Bundle\MainBundle\Entity\Locale
            - ~
            
    araneum.main.admin.component:
        class: Araneum\Bundle\MainBundle\Admin\ComponentAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Main", label: "Component" }
        arguments:
            - ~
            - Araneum\Bundle\MainBundle\Entity\Component
            - ~
        calls:
            - [setDispatcher, [@event_dispatcher]]

    araneum.main.admin.application:
            class: Araneum\Bundle\MainBundle\Admin\ApplicationAdmin
            tags:
                - { name: sonata.admin, manager_type: orm, group: "Main", label: "Application" }
            arguments:
                - ~
                - Araneum\Bundle\MainBundle\Entity\Application
                - ~
            calls:
                - [setSecurityToken, [@security.token_storage]]
                - [setDispatcher, [@event_dispatcher]]
