services:
    sonata.admin.connection:
        class: Araneum\Bundle\MainBundle\Admin\ConnectionAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Connection", label: "Connection" }
        arguments:
            - ~
            - Araneum\Bundle\MainBundle\Entity\Connection
            - ~
        calls:
            - [setTranslationDomain, [AraneumBundle]]