services:
    sonata.admin.post:
        class: Araneum\Bundle\MainBundle\Admin\LocaleAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Post" }
        arguments:
            - ~
            - Araneum\Bundle\MainBundle\Entity\Locale
            - ~
        calls:
            - [ setTranslationDomain, [AraneumMainBundle]]