services:
    araneum.main.admin.cluster:
        class: Araneum\Bundle\MainBundle\Admin\ClusterAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Main", label: "Cluster" }
        arguments:
            - ~
            - Araneum\Bundle\MainBundle\Entity\Cluster
            - ~
            
    araneum.main.admin.connection:
        class: Araneum\Bundle\MainBundle\Admin\ConnectionAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Main", label: "Connection" }
        arguments:
            - ~
            - Araneum\Bundle\MainBundle\Entity\Connection
            - ~
        calls:
            - [setTemplate, [list, AraneumMainBundle:Admin:list.html.twig]]
            
    araneum.main.admin.locale:
        class: Araneum\Bundle\MainBundle\Admin\LocaleAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Main", label: "Locale" }
        arguments:
            - ~
            - Araneum\Bundle\MainBundle\Entity\Locale
            - ~
            
    araneum.main.admin.component:
        class: Araneum\Bundle\MainBundle\Admin\ComponentAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Main", label: "Component" }
        arguments:
            - ~
            - Araneum\Bundle\MainBundle\Entity\Component
            - ~

    araneum.main.admin.application:
            class: Araneum\Bundle\MainBundle\Admin\ApplicationAdmin
            tags:
                - { name: sonata.admin, manager_type: orm, group: "Main", label: "Application" }
            arguments:
                - ~
                - Araneum\Bundle\MainBundle\Entity\Application
                - SonataAdminBundle:CRUD
            calls:
                - [setContainer, [@service_container]]
