services:
    araneum.main.application.handler:
        class: Araneum\Bundle\MainBundle\Service\ApplicationHandlerService
        arguments: [@doctrine.orm.entity_manager, Araneum\Bundle\MainBundle\Entity\Application]

    araneum.main.cluster.handler:
        class: Araneum\Bundle\MainBundle\Service\ClusterHandlerService
        arguments: [@doctrine.orm.entity_manager, Araneum\Bundle\MainBundle\Entity\Cluster]