services:
    araneum.main.application.handler:
        class: Araneum\Bundle\MainBundle\Service\ApplicationHandlerService
        arguments:
            - @doctrine.orm.entity_manager
            - Araneum\Bundle\MainBundle\Entity\Application

    araneum.main.application.remote_manager:
        class: Araneum\Bundle\MainBundle\Service\RemoteApplicationManagerService
        arguments:
            - @doctrine.orm.entity_manager

    araneum.main.application.event_listener:
        class: Araneum\Bundle\MainBundle\Service\ApplicationEventListenerService
        arguments:
            - @service_container
        tags:
            - { name: kernel.event_listener, event: araneum.main.application.event.post_update, method: postUpdate }