services:
    araneum.main.handler.application:
        class: Araneum\Bundle\MainBundle\Handler\ApplicationHandler
        arguments: [@doctrine.orm.entity_manager, Araneum\Bundle\MainBundle\Entity\Application]

    araneum.main.service.application_manager:
        class: Araneum\Bundle\MainBundle\Service\ApplicationManager
        arguments: [@doctrine]