parameters:
    araneum.main.application.class: Araneum\Bundle\MainBundle\Entity\Application

services:
    araneum.main.handler.application:
        class: Araneum\Bundle\MainBundle\Handler\ApplicationHandler
        arguments: [@doctrine.orm.entity_manager, %araneum.main.application.class%]