services:
    araneum.main.handler.application:
        class: Araneum\Bundle\MainBundle\Handler\ApplicationHandler
        arguments: [@doctrine.orm.entity_manager, Araneum\Bundle\MainBundle\Entity\Application]

    araneum.main.service.remote_application_manager_service:
        class: Araneum\Bundle\MainBundle\Service\RemoteApplicationManagerService
        arguments: [@doctrine.orm.entity_manager]