services:
    araneum.main.application.handler:
        class: Araneum\Bundle\MainBundle\Service\ApplicationHandlerService
        arguments: [@doctrine.orm.entity_manager, Araneum\Bundle\MainBundle\Entity\Application]