services:
  araneum.mail.mail.api_handler:
    class: Araneum\Bundle\MailBundle\Service\MailApiHandlerService
    arguments: [@doctrine.orm.entity_manager, @form.factory, @araneum.main.service.application_manager]