<?php

namespace Araneum\Bundle\MailBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Araneum\Bundle\MailBundle\Entity\Mail;
use Araneum\Bundle\MailBundle\Entity\MailLog;

/**
 * MailLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MailLogRepository extends EntityRepository
{
    /**
     * Set Mail log
     * @param Mail $mail
     * @param int  $status
     * @throws \Exception
     */
    public function setMailLog(Mail $mail, $status)
    {
        $manager = $this->getEntityManager();
        try {
            $eMailLog = new MailLog();
            $eMailLog->setStatus($status);
            $eMailLog->setMail($mail);
            $manager->persist($eMailLog);
            $manager->flush();
        } catch (\Exception $e) {
            throw new \Exception('Dont save in MailLog.');
        }
    }
}
