<?php

namespace Araneum\Bundle\MailBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MailRepository extends EntityRepository
{
    /**
     * Return query with one mail
     *
     * @return \Doctrine\ORM\Query
     */
    public function getOneMail(){
        $qb = $this->createQueryBuilder('mail');

        $qb->select('m')->from('AraneumMailBundle:Mail','m');

        return $qb->getQuery()->getSingleResult();
    }

}
