services:
    araneum.auth.entry_point:
        class: Araneum\Base\Symfony\Security\AuthenticationEntryPoint

    araneum.auth.success.handler:
        class: Araneum\Base\Symfony\Security\AuthenticationSuccessHandler

    araneum.auth.failure.handler:
        class: Araneum\Base\Symfony\Security\AuthenticationFailureHandler
        arguments:
            - "@security.csrf.token_manager"

    araneum_datatable:
        class: Araneum\Base\Ali\DatatableBundle\Util\AraneumDatatable
        arguments:
            - "@service_container"
            - "@araneum_datatable.query_bilder"

    araneum_datatable.query_bilder:
        class: Araneum\Base\Ali\DatatableBundle\Util\Factory\Query\AraneumDoctrineBuilder
        arguments:
            - "@service_container"
            - "@doctrine.orm.default_entity_manager"
        tags:
            - { name: xmlm_datatable_query_bilder }

    araneum_datatable.factory:
        class: Araneum\Base\Ali\DatatableBundle\Util\Factory\DatatableFactory
        arguments:
            - "@araneum_datatable"
            - "@doctrine"
            - "@templating"
            - "@annotation_reader"
            - "@security.token_storage"

    araneum.base.form.handler:
        class: Araneum\Base\Service\FormHandlerService

    araneum.form_exporter.service:
        class: Araneum\Base\Service\FromExporterService
        arguments:
            - "@jms_serializer"
            - "@form.factory"

    araneum.admin.initializer.service:
        class: Araneum\Base\Service\AdminInitializerService
        arguments:
            - "@araneum.form_exporter.service"
            - "@araneum_datatable.factory"
            - "@araneum.action.factory"

    araneum.action.factory:
        class: Araneum\Base\Service\Actions\ActionFactory
        arguments:
            - "@araneum.action.builder"

    araneum.action.builder:
        class: Araneum\Base\Service\Actions\ActionBuilder
        arguments:
            - "@router"

    araneum.command_runner.service:
        class: Araneum\Base\Service\CommandRunnerService
        arguments:
            - "%kernel.root_dir%"

    araneum.base.rabbitmq.msg_convert_helper:
        class: Araneum\Base\Service\RabbitMQ\MessageConversionHelper

    araneum.base.spot_api:
        class: Araneum\Base\Service\Spot\SpotApiSenderService
        arguments:
            - "@guzzle.client"
            - "@doctrine.orm.entity_manager"
            - "%spot_enable_json_responce%"

    araneum.base.application_api:
        class: Araneum\Base\Service\Application\ApplicationApiSenderService
        arguments:
            - "@guzzle.client"
            - "@doctrine.orm.entity_manager"
            - "%spot_enable_json_responce%"
