services:
    araneum.base.form.handler:
        class: Araneum\Base\Service\FormHandlerService

    araneum.form_exporter.service:
        class: Araneum\Base\Service\FromExporterService
        arguments: [@jms_serializer, @form.factory]

    araneum.admin.initializer.service:
        class: Araneum\Base\Service\AdminInitializerService
        arguments: [@araneum.form_exporter.service]