services:
    araneum_authentication:
        class: Araneum\Base\Symfony\Security\AuthenticationEntryPoint

    araneum_datatable:
        class: Araneum\Base\Ali\DatatableBundle\Util\AraneumDatatable
        arguments: [@service_container, @araneum_datatable.query_bilder]

    araneum_datatable.query_bilder:
        class: Araneum\Base\Ali\DatatableBundle\Util\Factory\Query\AraneumDoctrineBuilder
        arguments: [@service_container, @doctrine.orm.default_entity_manager]
        tags:
            - { name: xmlm_datatable_query_bilder }

    araneum_datatable.factory:
        class: Araneum\Base\Ali\DatatableBundle\Util\Factory\DatatableFactory
        arguments: [@araneum_datatable, @doctrine, @templating, @annotation_reader, @security.token_storage]

    araneum.base.form.handler:
        class: Araneum\Base\Service\FormHandlerService

    araneum.form_exporter.service:
        class: Araneum\Base\Service\FromExporterService
        arguments: [@jms_serializer, @form.factory]

    araneum.admin.initializer.service:
        class: Araneum\Base\Service\AdminInitializerService
        arguments: [@araneum.form_exporter.service, @araneum_datatable.factory, @araneum.action.factory]

    araneum.action.factory:
        class: Araneum\Base\Service\Actions\ActionFactory
        arguments: [@araneum.action.builder]

    araneum.action.builder:
        class: Araneum\Base\Service\Actions\ActionBuilder
        arguments: [@router]

    araneum.command_runner.service:
        class: Araneum\Base\Service\CommandRunnerService
        arguments: [%kernel.root_dir%]

    araneum.base.rabbitmq.msg_convert_helper:
        class: Araneum\Base\Service\RabbitMQ\MessageConversionHelper

    araneum.base.rabbitmq.producer.spot:
        class: Araneum\Base\Service\RabbitMQ\SpotProducerService
        arguments:
            - @old_sound_rabbit_mq.spot_producer
            - @araneum.base.rabbitmq.msg_convert_helper
            - %rabbitmq_queue_expiration%

    araneum.base.rabbitmq.consumer.spot:
        class: Araneum\Base\Service\RabbitMQ\SpotConsumerService
        arguments: [@araneum.base.spot_api, @araneum.base.rabbitmq.msg_convert_helper]

    araneum.base.spot_api:
        class: Araneum\Base\Service\Spot\SpotApiSenderService
        arguments: [@guzzle.client, %spot_enable_json_responce%]