services:
  araneum.customer.customer.api_handler:
    class: Araneum\Bundle\CustomerBundle\Service\CustomerApiHandlerService
    arguments: [@doctrine.orm.entity_manager, @araneum.main.application_manager, @form.factory]