services:
    sonata.admin.locale:
        class: Araneum\Bundle\MainBundle\Admin\LocaleAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Locale", label: "Locale" }
        arguments:
            - ~
            - Araneum\Bundle\MainBundle\Entity\Locale
            - ~