services:
    sonata.admin.cluster:
        class: Araneum\Bundle\MainBundle\Admin\ClusterAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Cluster", label: "Cluster" }
        arguments:
            - ~
            - Araneum\Bundle\MainBundle\Entity\Cluster
            - ~
            
    sonata.admin.connection:
        class: Araneum\Bundle\MainBundle\Admin\ConnectionAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Connection", label: "Connection" }
        arguments:
            - ~
            - Araneum\Bundle\MainBundle\Entity\Connection
            - ~
            
    sonata.admin.locale:
        class: Araneum\Bundle\MainBundle\Admin\LocaleAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Locale", label: "Locale" }
        arguments:
            - ~
            - Araneum\Bundle\MainBundle\Entity\Locale
            - ~
            
    araneum.main.admin.component:
        class: Araneum\Bundle\MainBundle\Admin\ComponentAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Components", label: "Component" }
        arguments:
            - ~
            - Araneum\Bundle\MainBundle\Entity\Component
            - ~

    sonata.admin.application:
            class: Araneum\Bundle\MainBundle\Admin\ApplicationAdmin
            tags:
                - { name: sonata.admin, manager_type: orm, group: "Application", label: "Application" }
            arguments:
                - ~
                - Araneum\Bundle\MainBundle\Entity\Application
                - ~
