<?php

namespace Araneum\Bundle\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ComponentRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class ComponentRepository extends EntityRepository
{
}
