services:
    araneum.user.authentication_handler:
        class: Araneum\Bundle\UserBundle\Service\AuthenticationHandler
        arguments: [@router, @session, @form.csrf_provider]
        tags:
            - { name: 'monolog.logger', channel: 'securirty' }

    araneum_user.user.filter.form:
        class: Araneum\Bundle\UserBundle\Form\Filter\UserFilterType
        arguments: [@doctrine, @service_container]
        tags:
            - { name: form.type, alias: araneum_user_filter }