services:
    araneum.user.authentication_handler:
        class: Araneum\Bundle\UserBundle\Service\AuthenticationHandler
        arguments: [@router, @session, @security.csrf.token_manager]
        tags:
            - { name: 'monolog.logger', channel: 'securirty' }

    araneum_user.user.form:
        class: Araneum\Bundle\UserBundle\Form\Type\UserType
        arguments: [@router]
        tags:
            - { name: form.type }

    araneum_user.user.filter.form:
        class: Araneum\Bundle\UserBundle\Form\Filter\UserFilterType
        arguments: [@doctrine, @service_container]
        tags:
            - { name: form.type, alias: araneum_user_filter }

    araneum.spot.api.customer.service:
            class: Araneum\Bundle\UserBundle\Service\Spot\SpotApiCustomerService
            arguments: ["@doctrine.orm.entity_manager", "@araneum.agent.spotoption.service"]