services:
    araneum.user.authentication_handler:
        class: Araneum\Bundle\UserBundle\Service\AuthenticationHandler
        arguments: [@router, @session, @security.csrf.token_manager]
        tags:
            - { name: 'monolog.logger', channel: 'securirty' }
