<?php

namespace Araneum\Bundle\AgentBundle\Repository;

use Araneum\Base\Repository\CountableTrait;
use Doctrine\ORM\EntityRepository;

/**
 * ErrorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ErrorRepository extends EntityRepository implements \Countable
{
    use CountableTrait;

    /**
     * Get received Errors from all Applications in last 24 hours
     *
     * @return array
     */
    public function getReceivedErrorsFromAppsInLast24H()
    {
        return $this->createQueryBuilder('ERR')
            ->select('APP.name', 'ERR.type', 'ERR.sentAt')
            ->leftJoin('ERR.application', 'APP')
            ->where('ERR.sentAt BETWEEN :start AND :end')
            ->orderBy('ERR.sentAt', 'ASC')
            ->setParameters(
                [
                    'start' => date('Y-m-d H:i:s', time() - 86400),
                    'end' => date('Y-m-d H:i:s', time()),
                ]
            )
            ->getQuery()
            ->getResult();
    }
}
