<?php

namespace Araneum\Bundle\AgentBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * LeadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LeadRepository extends EntityRepository
{
	/**
	 * Find list of leads by email and/or phone as optionality
	 *
	 * @param array $filters
	 * @return array
	 */
	public function findByFilter($filters = [])
	{
		$queryBuilder = $this->createQueryBuilder('l');

		if (isset($filters['email']) && preg_match('/[\w\d\.\-\@]{3,}/', $filters['email'])) {
			$queryBuilder->where('l.email LIKE :email')
				->setParameter('email', $filters['email'].'%');
		}

		if (isset($filters['phone']) && preg_match('/[0-9\-\(\)]{3,17}/', $filters['phone'])) {
			$queryBuilder->andWhere('l.phone LIKE :phone')
				->setParameter('phone', $filters['phone'].'%');
		}

		return $queryBuilder->getQuery()->getResult();
	}
}
